const en = {
  login: "Login",
  register: "Register",
  logout: "Logout",
  logging_out: "Logging out",
  email: "Email",
  password: "Password",
  confirm_password: "Confirm password",
  not_found: "Not found",
  error: "Error",
  success: "Success",
  user_registered_successfully: "User registered successfully",
  user_login_successful: "User logged in successfully",
  file_uploaded_success: "File uploaded successfully",
  file_deleted_success: "File deleted successfully",
  file_not_found: "File could not be found",
  wont_share_email: "We'll never share your email.",
  error_occurred_refresh_page: "An error occurred. Please refresh this page",
  select_language: "Select language",
  passwords_dont_match: "Password dont match",
  "auth/configuration-not-found": "Authentication configuration has not been set for this app. Contact support",
  "auth/invalid-login-credentials": "Username or password provided was wrong. Please try again.",

}
export default en;