const he = {
  internal_error: "שגיאה פנימית",
  english: "אנגלית",
  hebrew: "עברית",
  login: "התחברות",
  home: "בית",
  files: "קבצים",
  register: "הרשמה",
  logout: "התנתקות",
  logging_out: "מתנתק...",
  email: "אימייל",
  password: "סיסמה",
  confirm_password: "אשר סיסמה",
  not_found: "לא נמצא",
  error: "שגיאה",
  success: "הצלחה",
  user_registered_successfully: "המשתמש נרשם בהצלחה",
  user_login_successful: "המשתמש התחבר בהצלחה",
  user_logout_successful: "המשתמש התנתק בהצלחה",
  file_uploaded_success: "הקובץ הועלה בהצלחה",
  file_deleted_success: "הקובץ נמחק בהצלחה",
  file_not_found: "לא ניתן למצוא את הקובץ",
  wont_share_email: "לא נחלק את האימייל שלך",
  error_occurred_refresh_page: "אירעה שגיאה. נסה לרענן את העמוד",
  select_language: "בחר שפה",
  passwords_dont_match: "הסיסמאות לא תואמות",
  upload_a_file_and_set_pages: "וודא שבחרת קובץ. אם מספר העמודים לא הושטע באופן אוטומטי, אנא הכנס את מספר העמודים",
  upload_file: "העלה קובץ",
  file: "קובץ",
  number_of_pages: "מספר עמודים",
  processing_file: "מעבד קובץ",
  information: "מידע",
  please_specify_number_of_pages: "בבקשה ציין את מספר העמודים",
  pages_approximated_for_word_doc: "שים לב שמספר העמודים הוא חיזוי במסמך Word. וודא שאתה מתאים את זה בהתאם",
  could_not_read_file: "לא ניתן לקרוא את הקובץ שהועלה. נסה קובץ אחר",
  download_file: "הורד קובץ",
  no_files_found: "לא נמצאו קבצים",
  "auth/configuration-not-found": "לא נמצאה הגדרת אימות לאפליקציה זו. צור קשר עם התמיכה",
  "auth/invalid-login-credentials": "שם משתמש או סיסמה שסופקו אינם נכונים. נסה שוב",
  "permission-denied": "אין לך הרשאה לגשת לעמוד זה. התחבר תחילה"
}

export default he;
